### ISSUE TITLE
Python 3.8.2 issue - tcl/tck

### ISSUE THREAD

**Issue by luial3** [corpnewt/ProperTree#21]
When I run the ProperTree.bat after installing python, the command prompt disappears. I open it manually on the command prompt and instead shows errors. Apparently it tries to find init.tcl in the wrong directory. It tries to look under "Python38-32/lib/tcl8.6" but it is under "Python38-32/tcl/tcl8.6". I Copied the tcl8.6 folder into the lib folder and another issue showed up.

It tries to look for the tck folder under tcl8.6. Unfortunately this is also in the wrong section. In the Python3.8.2 installation, the tck folder is under the tcl folder as well. I just copied the tck folder from "Python38-32/tcl" into the copies tcl folder "Python38-32/lib/tcl". I think these folders may have moved around and that has not been taken into account somewhere. Hopefully this helps as this is the second machine I have ran into this issue when installing Python

**Comment by corpnewt** [comment]
Can you send the exact output you get when running the .bat or .command file directly?

**Comment by luial3** [comment]
Traceback (most recent call last):
  File "C:\Users\Al\Desktop\ProperTree-master\ProperTree.command", line 554, in <module>
    p = ProperTree(plists)
  File "C:\Users\Al\Desktop\ProperTree-master\ProperTree.command", line 21, in __init__
    self.tk = tk.Tk()
  File "C:\Program Files (x86)\Python38-32\lib\tkinter\__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    {C:\Program Files (x86)\CSR\BlueSuite 2.6.6} {C:/Program Files (x86)/Python38-32/lib/tcl8.6} {C:/Program Files (x86)/lib/tcl8.6} C:/lib/tcl8.6 {C:/Program Files (x86)/library} C:/library C:/tcl8.6.9/library C:/tcl8.6.9/library



This probably means that Tcl wasn't installed properly.

**Comment by luial3** [comment]
Traceback (most recent call last):
  File "C:\Users\Al\Desktop\ProperTree-master\ProperTree.command", line 554, in <module>
    p = ProperTree(plists)
  File "C:\Users\Al\Desktop\ProperTree-master\ProperTree.command", line 21, in __init__
    self.tk = tk.Tk()
  File "C:\Program Files (x86)\Python38-32\lib\tkinter\__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable tk.tcl in the following directories:
    {C:/Program Files (x86)/Python38-32/lib/tcl8.6/tk8.6} {C:/Program Files (x86)/Python38-32/lib/tk8.6} {C:/Program Files (x86)/lib/tk8.6} {C:/Program Files (x86)/lib/tk8.6} C:/lib/tk8.6 {C:/Program Files (x86)/library}



This probably means that tk wasn't installed properly.


C:\Users\Al\Desktop\ProperTree-master>

**Comment by luial3** [comment]
The second output is when I copy the tcl8.6 folder into lib

**Comment by corpnewt** [comment]
If I get time today, I'll install the latest python on my Windows machine and see if I suffer the same issue.  This appears to be out of the scope of this script though - as it's an issue with tkinter initializing.

-CorpNewt

**Comment by luial3** [comment]
After I copy the tk8.6 folder into the new tcl folder, the issue is fixed and it opens, leaving me to think its a simple change in location issue

**Comment by corpnewt** [comment]
Yeah - even on their current [reference page](https://docs.python.org/3/library/tkinter.html) for Tkinter, they initialize it the same way I am in ProperTree:
```py
root = tk.Tk()
```
So I'm guessing it's either an issue with 3.8.2 - or the local install.  I'll still test and update here - but unless others come forth with the same issue, I'll likely close this in a few days.

-CorpNewt

**Comment by altinselimi** [comment]
Experiencing same issue...

**Comment by Yash-Garg** [comment]
I'm having the same issue! I tried installing Python 2.7.2 but it still showed up the same issue and didn't work with python3.8 too

**Comment by luial3** [comment]
If you read my post thoroughly youll see that I posted a workaround. Copy
and paste some files onto the directory necessary and that Should work. Its
only a temp fix, but at least it works

**Comment by Yash-Garg** [comment]
Thank you @luial3 ! I'll take a look

**Comment by Yash-Garg** [comment]
@luial3 i tried copying `tcl` folder under Lib in **Python38** and **Python38-32** but the issue still persists :(

**Comment by luial3** [comment]
Oh interesting, open the propertree program using command prompt. It should
tell you what the issue is instead of automatically closing. Thats how i
found it was the tlc in my case

**Comment by Yash-Garg** [comment]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Yashg\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Yashg\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 804, in callit
    func(*args)
  File "C:\Users\Yashg\Documents\macOS - Stuff\ProperTree-master\ProperTree.command", line 205, in <lambda>
    self.tk.after(100, lambda:self.check_open(plists))
  File "C:\Users\Yashg\Documents\macOS - Stuff\ProperTree-master\ProperTree.command", line 243, in check_open
    self.start_window = self.new_plist()
  File "C:\Users\Yashg\Documents\macOS - Stuff\ProperTree-master\ProperTree.command", line 465, in new_plist
    window = plistwindow.PlistWindow(self, self.tk)
NameError: name 'plistwindow' is not defined
```

This exception is coming up when i am trying to run the ProperTree.bat file.

**Comment by luial3** [comment]
I may be wrong but i thunk youre running the wrong file. That is pointing
to the .command file. Youre using windows which uses the other file, .bat
or . Cmd i forget... try that one, if not try the .py file

**Comment by Yash-Garg** [comment]
@luial3 i am running .bat file only, it executes the command file ! And tried python one too it just opens for a second and closes

**Comment by luial3** [comment]
Yeah, this is a separate issue from my own, unfortunately. I would post a
new issue with the output you just received. Also, try running the .py file
using command prompt as well, Thats the only way to view the errors

**Comment by Yash-Garg** [comment]
@luial3 Okay so i tried on my other laptop and it works there with Python 3.8, don't know why it didn't work on the first one ! Thank you for the quick replies.

**Comment by siralexmu** [comment]
How can I run ProperTree on linux? Sorry for asking a dumb question.
